name: Build and Publish Image to DockerHub

on:
  push:
    branches:
      - main
    paths:
        - 'api/Dockerfile'
        - 'front-end-nextjs/Dockerfile'

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Image
        run: |
          docker build ./api/ -t kgroy107/devops-qr-code-backend:latest
          docker build ./front-end-nextjs/ -t kgroy107/devops-qr-code-frontend:latest

      - name: Push Image to Docker
        run: |
          docker login -u kgroy107 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push kgroy107/devops-qr-code-backend:latest
          docker push kgroy107/devops-qr-code-frontend:latest
